server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    #拉取服务的间隔时间
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:10086/eureka
zuul:
  # 路由路径前缀
  prefix: /api
  routes:
    #路由到商品的微服务
    item-service: /item/**
    #路由到搜索微服务
    search-service: /search/**
    #路由到用户微服务
    user-service: /user/**
    #路由到授权微服务
    auth-service: /auth/**
    #路由到购物车微服务
    cart-service: /cart/**
    #路由到订单微服务
    order-service: /order/**

  #是否携带域名头信息
  add-host-header: true
  #覆盖默认敏感头信息
  sensitive-headers:
leyou:
  jwt:
    # 公钥地址
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub
    # cookie名字
    cookieName: LY_TOKEN
  filter:
    #过滤器白名单
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item