#此微服务端口
server:
  port: 8087
#微服务名称
spring:
  application:
    name: auth-service
#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    #拉取服务时间
    registry-fetch-interval-seconds: 10
  instance:
    # 每隔5秒发送一次心跳
    lease-renewal-interval-in-seconds: 5
    # 10秒不发送就过期
    lease-expiration-duration-in-seconds: 10
leyou:
  jwt:
    # 登录校验的密钥(salt--盐)
    secret: leyou@Login(Auth}*^31)&heiMa%
    # 公钥地址
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub
    # 私钥地址
    priKeyPath: C:\\tmp\\rsa\\rsa.pri
    # 过期时间,单位分钟
    expire: 30
    # cookie名字
    cookieName: LY_TOKEN