server:
  port: 8084
spring:
  application:
    name: goods-web
  #是否缓存
  thymeleaf:
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    # 每隔5秒发送一次心跳
    lease-renewal-interval-in-seconds: 5
    # 10秒不发送就过期
    lease-expiration-duration-in-seconds: 10