server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.150.128
    virtual-host: /leyou
    username: leyou
    password: leyou

#短信服务
leyou:
  sms:
    # 你自己的accessKeyId
    accessKeyId: JWffwFJIwada
    # 你自己的AccessKeySecret
    accessKeySecret: aySRliswq8fe7rF9gQyy1Izz4MQ
    # 签名名称
    signName: 乐优商城
    # 模板名称
    verifyCodeTemplate: SMS_133976814