#端口
server:
  port: 10086
#服务名
spring:
  application:
    name: leyou-registry
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
    # 把自己注册到eureka服务列表
    register-with-eureka: false
    # 拉取eureka服务信息
    fetch-registry: false
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 每隔5秒钟，进行一次服务列表的清理
    eviction-interval-timer-in-ms: 5000